import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Geist } from "next/font/google";
import { Montserrat } from "next/font/google";

import Navbar from "@/components/general/Navabr/Navbar";
import { Inter } from "next/font/google";
import Footer from "@/components/general/Footer";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/general/theme-provider";
const inter = Inter({ subsets: ["latin"] });
const geist = Geist({
  subsets: ["latin"],
});
const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${montserrat}   ${inter.className}  ${geist}  antialiased`}
        >
          <ThemeProvider attribute="class" enableSystem defaultTheme="system">
            <Navbar />
            <div className="px-4 md:px-12 lg:px-20">
              {children}
              <Toaster />
            </div>
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
