export const jobListings = [
  {
    title: "AI/ML Engineer",
    company: "Apple",
    icon_url: "https://cdn.brandfetch.io/idnrCPuv87/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "London",
    level: "Entry Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "UX Designer",
    company: "Intel",
    icon_url: "https://cdn.brandfetch.io/idTGhLyv09/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Mumbai",
    level: "Senior Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 4 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "DevOps Engineer",
    company: "Amazon",
    icon_url: "https://cdn.brandfetch.io/idawOgYOsG/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "California",
    level: "Senior Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 6 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Cloud Engineer",
    company: "Microsoft",
    icon_url: "https://cdn.brandfetch.io/idchmboHEZ/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Bangalore",
    level: "Entry Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 4 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "UX Designer",
    company: "IBM",
    icon_url: "https://cdn.brandfetch.io/idXPdmxrE6/w/400/h/400/theme/dark/icon.jpeg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "New York",
    level: "Intermediate Level",
    ctc: "CTC: 120k",
    apply_label: "Apply Now",
    posted: "Posted 9 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Product Manager",
    company: "Apple",
    icon_url: "https://cdn.brandfetch.io/idnrCPuv87/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Austin",
    level: "Senior Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 11 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Data Analyst",
    company: "Microsoft",
    icon_url: "https://cdn.brandfetch.io/idchmboHEZ/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "London",
    level: "Senior Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 2 months ago",
    description:
      "As a Data Analyst, you will interpret complex data sets, provide actionable insights, and support data-driven decision-making.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Backend Developer",
    company: "Google",
    icon_url: "https://cdn.brandfetch.io/id6O2oGzv-/theme/dark/symbol.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Austin",
    level: "Senior Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 7 months ago",
    description:
      "As a Backend Developer, you'll develop scalable server-side applications, manage APIs, and work closely with frontend and DevOps teams.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Product Manager",
    company: "Salesforce",
    icon_url: "https://cdn.brandfetch.io/idVE84WdIN/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Washington",
    level: "Intermediate Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 7 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "AI/ML Engineer",
    company: "Salesforce",
    icon_url: "https://cdn.brandfetch.io/idVE84WdIN/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Bangalore",
    level: "Intermediate Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 9 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Product Manager",
    company: "Netflix",
    icon_url: "https://cdn.brandfetch.io/id1I-aPSS5/w/227/h/91/theme/dark/logo.png?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "New York",
    level: "Senior Level",
    ctc: "CTC: 110k",
    apply_label: "Apply Now",
    posted: "Posted 4 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Product Manager",
    company: "Google",
    icon_url: "https://cdn.brandfetch.io/id6O2oGzv-/theme/dark/symbol.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "London",
    level: "Entry Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 9 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "AI/ML Engineer",
    company: "Amazon",
    icon_url: "https://cdn.brandfetch.io/idawOgYOsG/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Chennai",
    level: "Intermediate Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 3 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Frontend Developer",
    company: "Adobe",
    icon_url: "https://cdn.brandfetch.io/id_KsyK7J9/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Mumbai",
    level: "Intermediate Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 11 months ago",
    description:
      "As a Frontend Developer, you will design interactive interfaces, optimize performance, and bring creative ideas to life using modern web technologies.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Data Analyst",
    company: "Netflix",
    icon_url: "https://cdn.brandfetch.io/id1I-aPSS5/w/227/h/91/theme/dark/logo.png?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "London",
    level: "Senior Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 6 months ago",
    description:
      "As a Data Analyst, you will interpret complex data sets, provide actionable insights, and support data-driven decision-making.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Product Manager",
    company: "IBM",
    icon_url: "https://cdn.brandfetch.io/idXPdmxrE6/w/400/h/400/theme/dark/icon.jpeg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Chennai",
    level: "Intermediate Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 7 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "UX Designer",
    company: "Amazon",
    icon_url: "https://cdn.brandfetch.io/idawOgYOsG/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Bangalore",
    level: "Entry Level",
    ctc: "CTC: 110k",
    apply_label: "Apply Now",
    posted: "Posted 9 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "AI/ML Engineer",
    company: "Apple",
    icon_url: "https://cdn.brandfetch.io/idnrCPuv87/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Washington",
    level: "Entry Level",
    ctc: "CTC: 130k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Product Manager",
    company: "Amazon",
    icon_url: "https://cdn.brandfetch.io/idawOgYOsG/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Toronto",
    level: "Senior Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 3 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Product Manager",
    company: "Amazon",
    icon_url: "https://cdn.brandfetch.io/idawOgYOsG/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "California",
    level: "Senior Level",
    ctc: "CTC: 120k",
    apply_label: "Apply Now",
    posted: "Posted 1 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Data Analyst",
    company: "Meta",
    icon_url: "https://cdn.brandfetch.io/idWvz5T3V7/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Chennai",
    level: "Entry Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 7 months ago",
    description:
      "As a Data Analyst, you will interpret complex data sets, provide actionable insights, and support data-driven decision-making.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Frontend Developer",
    company: "Apple",
    icon_url: "https://cdn.brandfetch.io/idnrCPuv87/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Bangalore",
    level: "Senior Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "As a Frontend Developer, you will design interactive interfaces, optimize performance, and bring creative ideas to life using modern web technologies.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Software Tester",
    company: "Apple",
    icon_url: "https://cdn.brandfetch.io/idnrCPuv87/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "California",
    level: "Entry Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 3 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Product Manager",
    company: "Apple",
    icon_url: "https://cdn.brandfetch.io/idnrCPuv87/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Toronto",
    level: "Senior Level",
    ctc: "CTC: 120k",
    apply_label: "Apply Now",
    posted: "Posted 3 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Frontend Developer",
    company: "IBM",
    icon_url: "https://cdn.brandfetch.io/idXPdmxrE6/w/400/h/400/theme/dark/icon.jpeg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Austin",
    level: "Intermediate Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 10 months ago",
    description:
      "As a Frontend Developer, you will design interactive interfaces, optimize performance, and bring creative ideas to life using modern web technologies.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "AI/ML Engineer",
    company: "Apple",
    icon_url: "https://cdn.brandfetch.io/idnrCPuv87/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Mumbai",
    level: "Senior Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 1 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Cloud Engineer",
    company: "Intel",
    icon_url: "https://cdn.brandfetch.io/idTGhLyv09/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Austin",
    level: "Entry Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Cloud Engineer",
    company: "Amazon",
    icon_url: "https://cdn.brandfetch.io/idawOgYOsG/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Toronto",
    level: "Intermediate Level",
    ctc: "CTC: 120k",
    apply_label: "Apply Now",
    posted: "Posted 8 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Software Tester",
    company: "Salesforce",
    icon_url: "https://cdn.brandfetch.io/idVE84WdIN/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Washington",
    level: "Senior Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "AI/ML Engineer",
    company: "IBM",
    icon_url: "https://cdn.brandfetch.io/idXPdmxrE6/w/400/h/400/theme/dark/icon.jpeg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "California",
    level: "Intermediate Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 7 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Backend Developer",
    company: "Microsoft",
    icon_url: "https://cdn.brandfetch.io/idchmboHEZ/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "New York",
    level: "Entry Level",
    ctc: "CTC: 110k",
    apply_label: "Apply Now",
    posted: "Posted 3 months ago",
    description:
      "As a Backend Developer, you'll develop scalable server-side applications, manage APIs, and work closely with frontend and DevOps teams.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Data Analyst",
    company: "Adobe",
    icon_url: "https://cdn.brandfetch.io/id_KsyK7J9/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "California",
    level: "Entry Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 6 months ago",
    description:
      "As a Data Analyst, you will interpret complex data sets, provide actionable insights, and support data-driven decision-making.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Data Analyst",
    company: "Microsoft",
    icon_url: "https://cdn.brandfetch.io/idchmboHEZ/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Toronto",
    level: "Senior Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 9 months ago",
    description:
      "As a Data Analyst, you will interpret complex data sets, provide actionable insights, and support data-driven decision-making.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Cloud Engineer",
    company: "Google",
    icon_url: "https://cdn.brandfetch.io/id6O2oGzv-/theme/dark/symbol.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Chennai",
    level: "Entry Level",
    ctc: "CTC: 110k",
    apply_label: "Apply Now",
    posted: "Posted 1 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Software Tester",
    company: "Netflix",
    icon_url: "https://cdn.brandfetch.io/id1I-aPSS5/w/227/h/91/theme/dark/logo.png?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Washington",
    level: "Entry Level",
    ctc: "CTC: 110k",
    apply_label: "Apply Now",
    posted: "Posted 6 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "UX Designer",
    company: "Google",
    icon_url: "https://cdn.brandfetch.io/id6O2oGzv-/theme/dark/symbol.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "New York",
    level: "Entry Level",
    ctc: "CTC: 130k",
    apply_label: "Apply Now",
    posted: "Posted 1 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Data Analyst",
    company: "Meta",
    icon_url: "https://cdn.brandfetch.io/idWvz5T3V7/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Hyderabad",
    level: "Senior Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 7 months ago",
    description:
      "As a Data Analyst, you will interpret complex data sets, provide actionable insights, and support data-driven decision-making.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "UX Designer",
    company: "Intel",
    icon_url: "https://cdn.brandfetch.io/idTGhLyv09/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "London",
    level: "Intermediate Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 3 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Security Analyst",
    company: "Apple",
    icon_url: "https://cdn.brandfetch.io/idnrCPuv87/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "New York",
    level: "Senior Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 4 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Backend Developer",
    company: "Salesforce",
    icon_url: "https://cdn.brandfetch.io/idVE84WdIN/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Hyderabad",
    level: "Intermediate Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "As a Backend Developer, you'll develop scalable server-side applications, manage APIs, and work closely with frontend and DevOps teams.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "UX Designer",
    company: "Salesforce",
    icon_url: "https://cdn.brandfetch.io/idVE84WdIN/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "California",
    level: "Entry Level",
    ctc: "CTC: 120k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "UX Designer",
    company: "Amazon",
    icon_url: "https://cdn.brandfetch.io/idawOgYOsG/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Mumbai",
    level: "Senior Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 6 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "UX Designer",
    company: "IBM",
    icon_url: "https://cdn.brandfetch.io/idXPdmxrE6/w/400/h/400/theme/dark/icon.jpeg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Chennai",
    level: "Intermediate Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 10 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Security Analyst",
    company: "Salesforce",
    icon_url: "https://cdn.brandfetch.io/idVE84WdIN/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Mumbai",
    level: "Intermediate Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 1 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Software Tester",
    company: "IBM",
    icon_url: "https://cdn.brandfetch.io/idXPdmxrE6/w/400/h/400/theme/dark/icon.jpeg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Austin",
    level: "Intermediate Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 11 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "UX Designer",
    company: "Salesforce",
    icon_url: "https://cdn.brandfetch.io/idVE84WdIN/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Bangalore",
    level: "Intermediate Level",
    ctc: "CTC: 130k",
    apply_label: "Apply Now",
    posted: "Posted 5 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "DevOps Engineer",
    company: "Meta",
    icon_url: "https://cdn.brandfetch.io/idWvz5T3V7/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Chennai",
    level: "Senior Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 6 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "UX Designer",
    company: "Google",
    icon_url: "https://cdn.brandfetch.io/id6O2oGzv-/theme/dark/symbol.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Austin",
    level: "Entry Level",
    ctc: "CTC: 120k",
    apply_label: "Apply Now",
    posted: "Posted 9 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "AI/ML Engineer",
    company: "Intel",
    icon_url: "https://cdn.brandfetch.io/idTGhLyv09/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Chennai",
    level: "Intermediate Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 12 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
  {
    title: "Frontend Developer",
    company: "Apple",
    icon_url: "https://cdn.brandfetch.io/idnrCPuv87/theme/dark/logo.svg?c=1dxbfHSJFAPEGdCLU4o5B",
    location: "Bangalore",
    level: "Intermediate Level",
    ctc: "CTC: 130k",
    apply_label: "Apply Now",
    posted: "Posted 12 months ago",
    description:
      "As a Frontend Developer, you will design interactive interfaces, optimize performance, and bring creative ideas to life using modern web technologies.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
  },
];
